name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Database Setup
        run: |
          python setup_database.py

      - name: Start Server
        run: |
          nohup python server.py &

      - name: Test Server
        run: |
          sleep 5  # Wait for the server to start
          curl http://localhost:8000/memos || echo "Server is not running"

      - name: Commit and Push Changes
        run: |
          git config --local user.email "your_email@example.com"
          git config --local user.name "Your Name"
          git add .
          git commit -m "Automated commit: Update server and database" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
